version: '3.4'

volumes:
    pgdata:
        driver: local

services:
    postgres:
        restart: always
        image: postgres:12.0-alpine
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./app:/app
        env_file:
            - dev.env
    background_tasks:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
        command: python manage.py process_tasks
        env_file:
            - dev.env
        depends_on:
            - postgres
            - app
    app:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
        ports:
            - 8000:8000
        command: >
            bash -c "python manage.py migrate --noinput || exit 1
            && python manage.py runserver 0.0.0.0:8000"
        env_file:
            - dev.env
        depends_on:
            - postgres