version: '3.4'

services:
    background_tasks:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
        env_file:
            - dev.env
        command: python manage.py process_tasks
    app:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
        ports:
            - 8000:8000
        command: >
            bash -c "python manage.py migrate --noinput || exit 1
            && python manage.py runserver 0.0.0.0:8000"
        env_file:
            - dev.env